batchprocession

diff --git a/Advanced_shell/batchProcessing-0x02 b/Advanced_shell/batchProcessing-0x02
--- a/Advanced_shell/batchProcessing-0x02
+++ b/Advanced_shell/batchProcessing-0x02
@@ -3,7 +3,9 @@
 
 # List of Pokémon
 POKEMON_LIST=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
+ERROR_FILE="errors.txt"
 
+success=false
 # Loop through each Pokémon
 for name in "${POKEMON_LIST[@]}"; do
     echo "Fetching data for $name..."
@@ -13,16 +15,24 @@ for name in "${POKEMON_LIST[@]}"; do
 
     # Output file path
     OUTPUT_FILE="$name.json"
+    for attempt in {1..3}; do
+        # Use curl to get data and save to file
+        curl -s "$API_URL" -o "$OUTPUT_FILE"
 
-    # Use curl to get data and save to file
-    curl -s "$API_URL" -o "$OUTPUT_FILE"
-
-    # Check if curl succeeded
-    if [ $? -eq 0 ]; then
-        echo "Saved data to $OUTPUT_FILE ✅"
-    else
-        echo "Failed to fetch data for $name ❌"
-    fi
+        # Check if curl succeeded
+        if [ $? -eq 0 ]; then
+            echo "Saved data to $OUTPUT_FILE ✅"
+            success=true
+            break
+        else
+            echo "Attempt $attempt failed for $name. Retrying..."
+            echo "Failed to fetch data for $name ❌"
+            echo "Something went wrong" >> "$ERROR_FILE"
+            echo "HTTP status code: $HTTP_STATUS" >> "$ERROR_FILE"
+            echo "Date: $(date)" >> "$ERROR_FILE"
+            echo "--------------------------------------" >> "$ERROR_FILE"
+            echo "Request failed. HTTP status code: $HTTP_STATUS. Errors saved to $ERROR_FILE."
+        fi
 
     # Wait for 1 second to avoid rate limiting
     sleep 1
